-- 테이블 생성전 무조건 삭제부터 (이미존재하는 테이블이 있을수도 있기때문)
DROP TABLE DEPARTMENT_TBL;
DROP TABLE EMPLOYEE_TBL;
DROP TABLE PROJECT_TBL;
DROP TABLE PROCEEDING_TBL;

CREATE TABLE DEPARTMENT_TBL(
    DEPT_NO         VARCHAR2(15)     NOT NULL 
  , DEPT_NAME       VARCHAR2(30)
  , DEPT_LOCATION   VARCHAR2(50)
  , CONSTRAINT PK_DPT PRIMARY KEY(DEPT_NO)
);

CREATE TABLE EMPLOYEE_TBL(
    EMP_NO          NUMBER          NOT NULL 
  , DEPT_NO         VARCHAR2(15)    
  , POSITION        CHAR(10)    
  , NAME            VARCHAR2(15)
  , HIRE_DATE       DATE
  , SALARY          NUMBER
  , CONSTRAINT PK_EMP PRIMARY KEY(EMP_NO)
  , CONSTRAINT FK_EPT_EMP FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL --부서가 사라지면 사원들의 해당부서만 NULL처리
);

CREATE TABLE PROJECT_TBL(
    PJT_NO          NUMBER          NOT NULL
  , PJT_NAME        VARCHAR2(30)    
  , BEGIN_DATE      DATE
  , END_DATE        DATE
  , CONSTRAINT PK_PJT PRIMARY KEY
);

CREATE TABLE PROCEEDING_TBL(
    PCD_NO          NUMBER          NOT NULL 
  , EMP_NO          NUMBER          NOT NULL
  , PJT_NO          NUMBER          NOT NULL
  , PJT_STATE       NUMBER          NOT NULL
  , CONSTRAINT PK_PCD PRIMARY KEY(PCD_NO)
  , CONSTRAINT FK_EMP_PR FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE_TBL(EMP_NO) ON DELETE CASCADE -- 사원이 삭제되면 프로젝트 진행명단에서 함께 삭제
  , CONSTRAINT FK_PJT_PR FOREIGN KEY(PJT_NO) REFERENCES PROJECT_TBL(PJT_NO)  ON DELETE CASCADE -- 프로젝트가 삭제되면 프로젝트 진행명단에서 함께 삭제
);

















