-- 테이블삭제 역순
DROP TABLE SCHEDULE_TBL;
DROP TABLE PLAYER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;

-- 국가 테이블 생성
CREATE TABLE NATION_TBL(
    N_CODE          NUMBER(3)       NOT NULL,
    N_NAME          VARCHAR2(30)    NOT NULL,
    N_PARTI_PERSON  NUMBER          CHECK(N_PARTI_PERSON = 0),
    N_PARTI_EVENT   NUMBER,
    N_PREV_RANK     NUMBER,
    N_CURR_RANK     NUMBER
);

-- 종목 테이블 생성
CREATE TABLE EVENT_TBL(
    E_CODE          NUMBER          NOT NULL,
    E_NAME          VARCHAR2(30)    NOT NULL,
    E_FIRST_YEAR    NUMBER(4),
    E_INFO          VARCHAR2(100)
);

-- 선수 테이블 생성
CREATE TABLE PLAYER_TBL(
    P_CODE          NUMBER(3)       NOT NULL,
    P_NAME          VARCHAR2(30),
    N_CODE          NUMBER(3)       NOT NULL,
    E_CODE          NUMBER          NOT NULL,
    P_RANK          NUMBER,
    P_AGE           NUMBER(3)  
);

-- 일정 테이블 생성
CREATE TABLE SCHEDULE_TBL(
    S_NO            NUMBER(3)       NOT NULL,
    N_CODE          NUMBER(3),
    E_CODE          NUMBER          ,
    S_START_DATE    DATE,
    S_END_DATE      DATE,
    S_INFO          VARCHAR2(100)
);

-- 기본키 추가
ALTER TABLE EVENT_TBL ADD CONSTRAINT PK_EVE PRIMARY KEY(E_CODE);
ALTER TABLE NATION_TBL ADD CONSTRAINT PK_NAT PRIMARY KEY(N_CODE);
ALTER TABLE PLAYER_TBL ADD CONSTRAINT PK_PY PRIMARY KEY(P_CODE);
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT PK_SCHE PRIMARY KEY(S_NO);

-- 외래키 추가
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_NAT_PY FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE);
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_EVE_PY FOREIGN KEY(E_CODE) REFERENCES EVENT_TBL(E_CODE);
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_NAT_SCHE FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE);
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_EVE_SCHE FOREIGN KEY(E_CODE) REFERENCES EVENT_TBL(E_CODE);

-- 국가 테이블 기본키 삭제하기.
-- 국가 테이블 기본키를 참조하는 외래키를 먼저 삭제해야 한다.
ALTER TABLE PLAYER_TBL DROP CONSTRAINT FK_NAT_PY;
ALTER TABLE SCHEDULE_TBL DROP CONSTRAINT FK_NAT_SCHE;
ALTER TABLE NATION_TBL DROP CONSTRAINT PK_NAT;

-- 선수 테이블의 FK_EVENT_PLAYER 외래키 일시중지하기
ALTER TABLE PLAYER_TBL DISABLE CONSTRAINT FK_EVE_PY;

-- 선수 테이블의 FK_EVENT_PLAYER 외래키 다시시작하기
ALTER TABLE PLAYER_TBL ENABLE CONSTRAINT FK_EVE_PY;

